name: CI Template

on:
  push:
    branches: [ develop, main ] # must be defined
  workflow_dispatch:

jobs:
  call-workflow-init:
   uses: DistributedCollective/.github/.github/workflows/init.yml@master
   with:
     ref: ${{ github.ref }}
     base_ref: ${{ github.base_ref }}
  call-workflow-docker-build:
    uses: DistributedCollective/.github/.github/workflows/docker.yml@master
    needs: [call-workflow-init]
    with:
      KUBE_NAMESPACE: ${{ needs.call-workflow-init.outputs.KUBE_NAMESPACE }}
      IMAGE_NAME: ${{ needs.call-workflow-init.outputs.image_name }}
      event_name: ${{ github.event_name }}
      registry: ${{ needs.call-workflow-init.outputs.registry }}
      dockerfile_path:  ${{ needs.call-workflow-init.outputs.dockerfile_path }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
